# Generated by Django 3.2.12 on 2022-02-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='notification',
            field=models.CharField(choices=[('За час', 1), ('За два ча0са', 2), ('За 4 часа', 4), ('За день', 24), ('За неделю', 168)], default=None, max_length=255, null=True),
        ),
    ]
